FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["div/div.csproj", "div/"]
RUN dotnet restore "div/div.csproj"
COPY . .
WORKDIR "/src/div"
RUN dotnet build "div.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "div.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "div.dll"]