apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-app
  labels:
    app: add-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-app
  template:
    metadata:
      labels:
        app: add-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "add-app"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: add-app
        ports:
        - containerPort: 3000
        imagePullPolicy: Always