apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-app
  labels:
    app: add-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add-app
  template:
    metadata:
      labels:
        app: add-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "add-app"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: add-app
        image: dapriotregistry.azurecr.io/addsample:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-registry