apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-app
  labels:
    app: audit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-app
  template:
    metadata:
      labels:
        app: audit-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "audit-app"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: audit-app
        image: dapriotregistry.azurecr.io/audit:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always