apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: "redisHost"
    value: "dapriotcache.redis.cache.windows.net:6380"
  - name: "redisPassword"
    value: "+JvTKb3g+1oKTzZRbg96mWHd0RZ3fvzXrycdBttsdQk="
  - name: enableTLS
    value: "true"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: default
spec:
  type: pubsub.redis
  metadata:
  - name: "redisHost"
    value: "dapriotcache.redis.cache.windows.net:6380"
  - name: "redisPassword"
    value: "+JvTKb3g+1oKTzZRbg96mWHd0RZ3fvzXrycdBttsdQk="
  - name: enableTLS
    value: "true"