apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: operations-store
spec:
  type: state.redis
  metadata:
  - name: "redisHost"
    value: "dapriotcache.redis.cache.windows.net:6380"
  - name: "redisPassword"
    value: "+JvTKb3g+1oKTzZRbg96mWHd0RZ3fvzXrycdBttsdQk="
  - name: enableTLS
    value: "true"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: calculator
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: Endpoint=sb://dapriobus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=j6Y+pv8FBacjouHM6pzNAv9rGDG/QVYYSwaczwbPy6Q=