apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-app
  labels:
    app: sub-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sub-app
  template:
    metadata:
      labels:
        app: sub-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "sub-app"
        dapr.io/port: "3001"
    spec:
      containers:
      - name: sub-app
        image: dapriotregistry.azurecr.io/sub:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-registry